# This is a basic workflow to help you get started with Actions

name: CI
on: push
jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            - name: Run a one-line script
              run: ./gradlew build
